### ISSUE TITLE
Unable to install pod

### ISSUE THREAD

**Issue by JulianRamirez** [CSolanaM/SkeletonUI#1]
Thank you for starting this project! I'm excited to check it out!

**Describe the bug**
While trying to do a new install of SkeletonUI, the pod install fails with the following error:
```
[!] Error installing SkeletonUI
[!] /usr/bin/git clone https://github.com/CSolanaM/SkeletonUI.git /var/folders/st/3lb8mpm938xfqktsrb3b62g80000gn/T/d20191029-96400-wf7mcw --template= --single-branch --depth 1 --branch 0.1.1

Cloning into '/var/folders/st/3lb8mpm938xfqktsrb3b62g80000gn/T/d20191029-96400-wf7mcw'...
warning: Could not find remote branch 0.1.1 to clone.
fatal: Remote branch 0.1.1 not found in upstream origin
```

**To Reproduce**
1. Start with a fresh project that does not have SkeletonUI installed
2. Add SkeletonUI to the podfile
3. Attempt to install the pods with `pod install`

**Expected behavior**
SkeletonUI is installed.

**Screenshots**
It's just the text above.

**Desktop (please complete the following information):**
- n/a

**Smartphone (please complete the following information):**
- n/a

**Additional context**
none

**Comment by CSolanaM** [comment]
Hi Julian,

Thank you very much for reporting the issue. There was a problem in the `.podspec` file, where the version didn't match the final available release, it was with the early beta versioning.

I've checked the whole setup and reuploaded to the Cocoapods repo. If you try again after updating your Cocoapods master repo by using `pod update`, it should work seamlessly.

Thanks!

**Comment by JulianRamirez** [comment]
Looks good! Thank you for the quick fix! I'm looking forward to trying this out.

For anyone else who may have this problem, I also had to do a `pod repo update` before `pod install` was able to succeed.
