### ISSUE TITLE
Error when running the example

### ISSUE THREAD

**Issue by nhathongly** [CSolanaM/SkeletonUI#15]
I got this error when running your example

SkeletonUI-macOS-iOS[1728:47422] Task <5ED5FF93-B549-451D-88B1-A54648BCBDA0>.<1> finished with error [-999] Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://rickandmortyapi.com/api/character/, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://rickandmortyapi.com/api/character/}

Can you give it a look?
Thanks

**Comment by CSolanaM** [comment]
It should be fixed in the latest commit both in develop & master branches
