### ISSUE TITLE
.primary color extension

### ISSUE THREAD

**Issue by marchettoartur** [CSolanaM/SkeletonUI#18]
In the AppearenceInteractor file you declare an extension to the Color type.
However this creates an error when I import this library in a file and in the same file use the stock Color.primary by Apple as there are two Color.primary and it is ambiguous.
Please rename it.

```swift
public static var primary: Color {
        #if os(iOS)
            return Color(.systemGray4)
        #elseif os(tvOS)
            return Color(.tertiaryLabel)
        #elseif os(watchOS)
            return Color.secondary
        #elseif os(macOS)
            return Color(.alternateSelectedControlColor)
        #endif
    }
}
```

**Comment by CSolanaM** [comment]
Hi @marchettoartur !

First of all, thanks for reporting this bug! I've been a bit busy lately, but the fix has been already merged thanks to the contribution of @alexandrethsilva !

Kind Regards,
