### ISSUE TITLE
When previewing, I get "use of unresolved identifier 'Process'"

### ISSUE THREAD

**Issue by kenmueller** [CSolanaM/SkeletonUI#2]
This only happens when previewing, and not when running the actual app. Unfortunately, I can't preview anywhere in the app now. iOS, SwiftUI

**Comment by CSolanaM** [comment]
Hi @kenmueller,

Thank you very much for reporting the issue. There was a problem on having SwiftLint and Swiftformat as a dependency of the library, they made the previews to fail like you were describing.

Please, do a `pod update` or update your package so you can get it updated.

Thanks!
