### ISSUE TITLE
Skeleton fills full height

### ISSUE THREAD

**Issue by maxtomczyk** [CSolanaM/SkeletonUI#25]
**Describe the bug**
Skeleton element uses full available height even in basic example. Occures on both, device and XCode preview.

**To Reproduce**
![Screenshot 2020-11-14 at 18 54 11](https://user-images.githubusercontent.com/20241462/99153732-cb2dbc00-26aa-11eb-95c3-d605e1fe5801.png)

**Expected behavior**
Skeleton uses height of one line of text

**Screenshots**
Uploaded in reproduction section

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 11.0.1 (20B29)

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus & XCode Preview
 - OS: iOS 14.2 (18B92)
**Additional context**

**Comment by pockerhead** [comment]
You can solve this problem by specifying maxHeight in the view

```
Text(role)
                    .skeleton(with: role.isNil)
                    .font(.system(size: 14,
                                  weight: .regular))
                    .foregroundColor(UIColor.descriptionTextColor.swiftUIColor)
                    .frame(maxHeight: 40)
```

I also made an extension for the View:
```
public extension View {
    func skeleton(with loading: Bool,
                  height: CGFloat?) -> some View {
        self.skeleton(with: loading,
                      transition: .opacity,
                      animated: .none)
            .frame(maxHeight: loading ? height : nil)
    }
}
```

**Comment by lawmaestro** [comment]
Unfortunately specifying `maxHeight` isn't really a solution since what if the text wraps and spans 2 or 3 lines? By fixing the max height on `Text` you end up clipping the text if you're not careful. Ideally the geometry reader used by `SkeletonUI` should be able to provide the right measured height of the text.

**Comment by charlesanim499** [comment]
@maxtomczyk Did you figure this out? any thoughts on this @CSolanaM

**Comment by maxtomczyk** [comment]
@charlesanim499 No, I just stop using this library.

**Comment by CSolanaM** [comment]
@maxtomczyk 

Sorry for the huge delay, I couldn't really invest some time here.

@charlesanim499 @lawmaestro @pockerhead 

I figured out a generic way that can be beneficial in different situations, as when there's a `View` of any kind that's skeletoning, the skeleton cannot guess the final size before it has its final form. It's just a size parameter that can be applied, but won't be used when the `View` draws its final form.

You can check that out in the branch (feature/SU-25_CustomSize) of this PR: https://github.com/CSolanaM/SkeletonUI/pull/34

Example:
<img width="827" alt="Captura de pantalla 2021-11-12 a las 16 58 04" src="https://user-images.githubusercontent.com/9338271/141496266-050383e1-de0b-4b0d-a9df-a78713167970.png">

That becomes:

https://user-images.githubusercontent.com/9338271/141496465-543b69e2-c7af-4219-a0fe-62c69134cfa7.mp4

And this:
<img width="821" alt="Captura de pantalla 2021-11-12 a las 17 00 27" src="https://user-images.githubusercontent.com/9338271/141496602-11f3f5ee-0491-4aaa-9af4-d6cda0f18c89.png">

Becomes:

https://user-images.githubusercontent.com/9338271/141496737-de6c7e24-64ca-4478-b3fe-5f2a11999516.mp4

**Comment by charlesanim499** [comment]
Thanks for the response @CSolanaM. I appreciate this library, for my implementation,

I found out Swift has the `.redacted()` modifier as part of its API. It works for my what I'm looking to achieve. Thank you for the hard work.

Thanks @maxtomczyk  maxtomczyk

**Comment by qweluke** [comment]
> @charlesanim499 No, I just stop using this library.

so which library are you using? or how you solve skeleton loading?

**Comment by CSolanaM** [comment]
> > @charlesanim499 No, I just stop using this library.
> 
> @ charlesanim499 so which library are you using? or how you solve skeleton loading?

@qweluke As I previously said, due to how SwiftUI works and the fact that the library doesn't know the final frame that the data will occupy, you just need to add a `.frame()` modifier specifying the desired height either through `.frame(height: xxx)` or `.frame(maxHeight: xxx)`

If the final text, after loading, ends up using more than one line, you should probably do something like `.frame(maxHeight: isLoading ? 40 : nil)`

This way you'll specify the height of the skeleton when showing and leave the Text to calculate its final bounds.
