### ISSUE TITLE
How do I get the index of the element

### ISSUE THREAD

**Issue by mejias1990** [CSolanaM/SkeletonUI#27]

**Comment by CSolanaM** [comment]
SkeletonUI's offers a couple of wrappers for `List` and `ForEach`, which try to behave the same way. Those are `SkeletonList` and `SkeletonForEach`. If you take a look to the code:

```
    public var body: some View {
        ForEach(0 ..< (data.isEmpty ? quantity : data.count), id: \.self) { index in
            self.content(self.data.isEmpty, self.data.isEmpty ? nil : self.data.map { $0 }[index])
        }
    }
```

Both gives you access to the `Data.Element` on the specified index. If you need to only access the index, you can either ask for `array.indexOf(element)` or better, create your own wrapper.
