### ISSUE TITLE
Animation Is not trigger

### ISSUE THREAD

**Issue by aluco100** [CSolanaM/SkeletonUI#41]
Hi There,

I'm trying to use the example to animate my skeleton. However, it's not getting animated.

**To Reproduce**
1. Use the following Code:

```
Text("Finished requesting users!")
                    .skeleton(with: true)
                    .appearance(type: .solid(color: .red, background: .blue))
                    .animation(type: .pulse())
                    .background(Color.black)
```

**Expected behavior**
It should be animated

**Screenshots**
<img width="446" alt="Captura de Pantalla 2022-08-08 a la(s) 19 01 12" src="https://user-images.githubusercontent.com/13009279/183528824-7f5e1090-5ad4-4233-a3c7-0f5b43ed7816.png">

What could be happening?

Best Regards

**Comment by CSolanaM** [comment]
I've been running into some issues regarding the animation in a side project where I'm also using it. It's a great way for debugging purposes in unusual contexts.

I've created a branch where I'm trying to address the fix I spotted, but as it is very related to yours, maybe could you try if it gets improved or solved?

Thanks

The branch is: `feature/SU-41_AnimationFixes`
