### ISSUE TITLE
iOS 17 Animation does not work + CPU overload + Leak

### ISSUE THREAD

**Issue by blyscuit** [CSolanaM/SkeletonUI#48]
Run the example project as iOS 17 and the Debug window shows a very bad CPU and RAM leak.

![Screenshot 2567-01-09 at 18 04 15](https://github.com/CSolanaM/SkeletonUI/assets/6356137/9aac0a94-03b3-4c22-ade3-34fb98df1974)

**Comment by CSolanaM** [comment]
Thanks @blyscuit for reporting this issue!

We're discussing @timdolenko's fix in his PR. Let's continue the conversation there. If you can test his branch on your end and give us extra feedback, it will be very appreciated.
